apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redhat-taro-002
  links:
  - url: https://openshift-gitops-server-openshift-gitops.apps.rosa.rosa-hcp-1544.kfnj.p3.openshiftapps.com/applications/openshift-gitops/redhat-taro-002-app
    title: ArgoCD
    icon: dashboard
  - url: https://redhat-taro-002-sc-demo-001.apps.rosa.rosa-hcp-1544.kfnj.p3.openshiftapps.com
    title: Application
    icon: dashboard
  - url: https://github.com/rhdh-skitamura-org/redhat-taro-002
    title: App Repository
    icon: dashboard
  annotations:
    argocd/app-selector: argocd.argoproj.io/instance=redhat-taro-002
    tektonci/build-namespace: sc-demo-001
    backstage.io/kubernetes-id: redhat-taro-002
    backstage.io/kubernetes-namespace: sc-demo-001
    janus-idp.io/tekton-enabled : 'true'
    janus-idp.io/tekton : redhat-taro-002
    backstage.io/techdocs-ref: url:https://github.com/rhdh-skitamura-org/redhat-taro-002
    github.com/project-slug: rhdh-skitamura-org/redhat-taro-002
    quay.io/repository-slug: skitamura-quay-org/sc-demo-001/redhat-taro-002
spec:
  type: api 
  system: "system:default/test-system-github"
  lifecycle: production
  owner: "user:default/skitamura7446"
  git: github
  git_host_url: github.com
  git_group_name: rhdh-skitamura-org
